# Site settings
title: "Harini Suvvari"
email: jacob@jacobtomlinson.co.uk
description: "A dark blog theme for Jekyll."
baseurl: ""
url: "http://carte-noire.jacobtomlinson.co.uk/"
title_description: "Harini Suvvari Personal website."
title_image: "https://avatars1.githubusercontent.com/u/12485697?v=3&u=1cd4d02b984dd0a1340e68f7806e86d9a7f2c63e&s=140"
google_analytics: "UA-20365477-4"
disqus_account: cartenoire
github_repository: https://github.com/jacobtomlinson/carte-noire
addthis_id: ra-513c6fa83da6ec67
post_limit: 5

# Social usernames/URLs
twitter_username: harini025
github_username:  gharini
linkedin_link: https://www.linkedin.com/in/harini-suvvari-55b91a1b
google_plus_link: http://carte-noire.jacobtomlinson.co.uk/


# Footer
footer_left: ""
footer_right: ""

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]
permalink: pretty
exclude: [vendor]
